import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const goToYHF = () => window.open("https://www.yellowhammerfund.org/", "_blank");

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>ScareBNB</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex-1 navbar bg-base-100">
                <div className="flex-row sm:flex-1">
                    <a onClick={goToYHF} className="text-xl normal-case text-error btn btn-ghost">
                        ScareBnB
                    </a>
                    <img onClick={goToYHF} src="/logo.png" alt="ScareBNB logo" />
                </div>
                <div className="flex-row sm:flex-1">
                    <button onClick={goToYHF} className="btn btn-primary">
                        Birmingham's Premier SPOOKY rental service
                    </button>
                </div>
                <div className="flex-none gap-2">
                    <div onClick={goToYHF} className="form-control">
                        <input type="text" placeholder="Search " className="input input-bordered" />
                    </div>
                    <div className="dropdown dropdown-end">
                        <label onClick={goToYHF} abindex="0" className="btn btn-ghost btn-circle avatar">
                            <div className="w-10 rounded-full">
                                <img src="https://api.lorem.space/image/face?hash=33791" />
                            </div>
                        </label>
                        <ul tabindex="0" className="p-2 mt-3 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52">
                            <li>
                                <a className="justify-between">
                                    Profile
                                    <span className="badge">New</span>
                                </a>
                            </li>
                            <li>
                                <a>Settings</a>
                            </li>
                            <li>
                                <a>Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <main className={`${styles.main} bg-[url('/bgcastle.jpg')] bg-cover bg-no-repeat flex-1`}>
                <div className="flex self-start px-10 py-4">
                    <h1 onClick={goToYHF} className="w-2/3 text-2xl font-extrabold text-base-100">
                        Go Find The Spookiest Stays of Birmingham
                    </h1>
                </div>
                <div className="flex self-start px-10 py-4">
                    <p onClick={goToYHF} className="w-1/3 prose text-base-100">
                        Who even reads this shit these days? Sure as fuck not me. Anyway, Birmingham's been around for a couple hundred years and it's haunted and shit I'm sure. Very spooky
                    </p>
                </div>
                <div className="flex self-start px-10 py-4">
                    <button onClick={goToYHF} className="w-2/3 btn btn-error">
                        Explore nearby
                    </button>
                </div>
            </main>
        </div>
    );
}
